---

- name: 'Install docker-machine'
  get_url:
    url: '{{ docker_compose_url }}'
    dest: '{{ docker_compose_bin }}'

- name: 'Make docker-compose executable'
  file:
    path: '{{ docker_compose_bin }}'
    mode: '0755'
    owner: 'root'
    group: 'root'