---

- name: Install dependencies
  apt:
    pkg: '{{ docker_dependencies }}'
    state: present
    cache_valid_time: 86400

- name: Install gpg key
  apt_key:
    keyserver: '{{ docker_gpg_keyserver }}'
    id: '{{ docker_gpg_id }}'
    state: present

- name: Add docker repository
  apt_repository:
    repo: '{{ docker_repository_url }}'
    state: present
    filename: docker

- name: Install docker
  apt:
    pkg: '{{ docker_apt_package }}'
    state: present

- name: Remove old ansible docker module
  apt:
    pkg:
      - python-dockerpty
      - python-docker
    state: absent
  when: not (ansible_distribution == 'Debian' and ansible_distribution_version|int <= 8)

- name: Install ansible docker module
  pip:
    name: docker
    state: present
