---

- name: Install dependencies
  apt:
    pkg: '{{ item }}'
    state: present
    cache_valid_time: 86400
  with_items: '{{ docker_dependencies }}'

- name: Install gpg key
  apt_key:
    keyserver: '{{ docker_gpg_keyserver }}'
    id: '{{ docker_gpg_id }}'
    state: present

- name: Add docker repository
  apt_repository:
    repo: '{{ docker_repository_url }}'
    state: present
    filename: docker

- name: Install docker
  apt:
    pkg: '{{ docker_apt_package }}'
    state: present

- name: 'Install python lib for ansible to manage docker (newer systems)'
  apt:
    pkg: python-dockerpty
    state: present
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 18)

- name: 'Install python lib for ansible to manage docker (older systems)'
  apt:
    pkg: python-docker
    state: present
  when: >
    (ansible_distribution == 'Debian' and ansible_distribution_version|int < 9) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 18)
