---

- name: 'Install docker-machine'
  shell:  'curl -L {{ docker_machine_url }} > {{ docker_machine_bin }}'
  args:
    creates: '{{ docker_machine_bin }}'
  tags: ['skip_ansible_lint']

- name: 'Make docker-machine executable'
  file:
    path: '{{ docker_machine_bin }}'
    mode: '0755'
    owner: 'root'
    group: 'root'