---

- name: 'Install docker-machine'
  get_url:
    url: '{{ docker_machine_url }}'
    dest: '{{ docker_machine_bin }}'

- name: 'Make docker-machine executable'
  file:
    path: '{{ docker_machine_bin }}'
    mode: '0755'
    owner: 'root'
    group: 'root'