---
- name: Install docker
  include: install.yml
  when: docker_install == true
  tags: ['docker-install']

- include: compose-install.yml
  when: docker_compose_install == true
  tags: ['docker-compose-install']

- include: machine-install.yml
  when: docker_machine_install == true
  tags: ['docker-machine-install']

#- include: configure.yml
#  when: docker_install == true
#  tags: ['docker-configure']

- name: Start docker
  service:
    name: 'docker'
    state: started
    enabled: yes
  changed_when: false # fix idempotence
  when: docker_start == true

- name: Handle swarm init
  include: swarm.yml
  tags: ['docker-swarm']